# Generated by Django 2.2.4 on 2019-09-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('user_no', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('work', models.CharField(max_length=256)),
                ('word', models.TextField()),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('p_word', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('score', models.IntegerField(default=90)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
